#!/usr/bin/env bash
# Entrypoint for the Tav_Lab Ansible control-node container.
# Installs the SSH keys, clones the repo on first run (pulls on later runs),
# then execs the CMD.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/tavaresm1/Tav_Lab.git}"
REPO_DIR="${REPO_DIR:-/home/ansible/Tav_Lab}"
REPO_BRANCH="${REPO_BRANCH:-main}"

KEY_SRC=/home/ansible/ssh_keys
SSH_DIR=/home/ansible/.ssh
KNOWN_HOSTS=/home/ansible/.ssh_state/known_hosts

# --- SSH keys ---------------------------------------------------------------
#
# control-node/ssh_keys/ is bind-mounted read-only at ${KEY_SRC}. Copy rather
# than use in place: SSH refuses a private key that is group- or world-readable,
# and the mode of a :ro mount comes from the host, where `chmod` inside the
# container fails with "Read-only file system".
#
#   ansible_control -> ~/.ssh/id_ed25519, the default identity -> root@tav-serv
#   autobase        -> ~/.ssh/autobase, matches ansible_ssh_private_key_file
#                      in group_vars/autobase_guests.yml -> ansible@ the guests
install_key() {
    local src="${KEY_SRC}/$1" dst="${SSH_DIR}/$2"
    if [[ -f "${src}" ]]; then
        install -m 600 "${src}" "${dst}"
        [[ -f "${src}.pub" ]] && install -m 644 "${src}.pub" "${dst}.pub"
        return 0
    fi
    return 1
}

mkdir -p "${SSH_DIR}"
chmod 700 "${SSH_DIR}"

missing=()
install_key ansible_control id_ed25519 || missing+=("ansible_control")
install_key autobase        autobase   || missing+=("autobase")

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "[entrypoint] WARNING: no SSH key found for: ${missing[*]}" >&2
    echo "[entrypoint]   Expected control-node/ssh_keys/<name> on the host." >&2
    echo "[entrypoint]   Generate them (control-node/README.md step 2):" >&2
    for m in "${missing[@]}"; do
        echo "[entrypoint]     ssh-keygen -t ed25519 -f ./ssh_keys/${m} -C \"${m}@tavares-lab\" -N ''" >&2
    done
    echo "[entrypoint]   Anything needing SSH will fail until then." >&2
fi

# known_hosts lives in the ssh_state volume so accepted host keys survive
# --rm. ~/.ssh itself is image-provided and resets every run.
mkdir -p "$(dirname "${KNOWN_HOSTS}")"
touch "${KNOWN_HOSTS}"
cat > "${SSH_DIR}/config" <<EOF
# Generated by control-node/entrypoint.sh on every start — edits are lost.
Host *
    UserKnownHostsFile ${KNOWN_HOSTS}
    StrictHostKeyChecking accept-new
    ServerAliveInterval 30
EOF
chmod 600 "${SSH_DIR}/config"

# --- Repo -------------------------------------------------------------------
if [[ ! -d "${REPO_DIR}/.git" ]]; then
    echo "[entrypoint] cloning ${REPO_URL} → ${REPO_DIR}"
    git clone --branch "${REPO_BRANCH}" "${REPO_URL}" "${REPO_DIR}"
else
    echo "[entrypoint] pulling ${REPO_BRANCH} in ${REPO_DIR}"
    git -C "${REPO_DIR}" fetch --quiet origin "${REPO_BRANCH}" || true
    git -C "${REPO_DIR}" checkout --quiet "${REPO_BRANCH}" || true
    git -C "${REPO_DIR}" pull --quiet --ff-only || true
fi

cd "${REPO_DIR}/ansible"
exec "$@"
