#!/usr/bin/env bash
# Entrypoint for the Tav_Lab Ansible control-node container.
# Installs the SSH keys, clones the repo on first run (pulls on later runs),
# then execs the CMD.

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/tavaresm1/Tav_Lab.git}"
REPO_DIR="${REPO_DIR:-/home/ansible/Tav_Lab}"
REPO_BRANCH="${REPO_BRANCH:-main}"

KEY_SRC=/home/ansible/ssh_keys
SSH_DIR=/home/ansible/.ssh
KNOWN_HOSTS=/home/ansible/.ssh_state/known_hosts

# --- SSH keys ---------------------------------------------------------------
#
# control-node/ssh_keys/ is bind-mounted read-only at ${KEY_SRC}. Copy rather
# than use in place: SSH refuses a private key that is group- or world-readable,
# and the mode of a :ro mount comes from the host, where `chmod` inside the
# container fails with "Read-only file system".
#
#   ansible_control -> ~/.ssh/id_ed25519, the default identity -> root@tav-serv
#   autobase        -> ~/.ssh/autobase, matches ansible_ssh_private_key_file
#                      in group_vars/autobase_guests.yml -> ansible@ the guests
install_key() {
    local src="${KEY_SRC}/$1" dst="${SSH_DIR}/$2"
    if [[ -f "${src}" ]]; then
        install -m 600 "${src}" "${dst}"
        [[ -f "${src}.pub" ]] && install -m 644 "${src}.pub" "${dst}.pub"
        return 0
    fi
    return 1
}

mkdir -p "${SSH_DIR}"
chmod 700 "${SSH_DIR}"

missing=()
install_key ansible_control id_ed25519 || missing+=("ansible_control")
install_key autobase        autobase   || missing+=("autobase")

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "[entrypoint] WARNING: no SSH key found for: ${missing[*]}" >&2
    echo "[entrypoint]   Expected control-node/ssh_keys/<name> on the host." >&2
    echo "[entrypoint]   Generate them (control-node/README.md step 2):" >&2
    for m in "${missing[@]}"; do
        echo "[entrypoint]     ssh-keygen -t ed25519 -f ./ssh_keys/${m} -C \"${m}@tavares-lab\" -N ''" >&2
    done
    echo "[entrypoint]   Anything needing SSH will fail until then." >&2
fi

# known_hosts lives in the ssh_state volume so accepted host keys survive
# --rm. ~/.ssh itself is image-provided and resets every run.
mkdir -p "$(dirname "${KNOWN_HOSTS}")"
touch "${KNOWN_HOSTS}"
cat > "${SSH_DIR}/config" <<EOF
# Generated by control-node/entrypoint.sh on every start — edits are lost.
Host *
    UserKnownHostsFile ${KNOWN_HOSTS}
    StrictHostKeyChecking accept-new
    ServerAliveInterval 30
EOF
chmod 600 "${SSH_DIR}/config"

# --- Repo -------------------------------------------------------------------
if [[ ! -d "${REPO_DIR}/.git" ]]; then
    echo "[entrypoint] cloning ${REPO_URL} → ${REPO_DIR}"
    git clone --branch "${REPO_BRANCH}" "${REPO_URL}" "${REPO_DIR}"
else
    echo "[entrypoint] pulling ${REPO_BRANCH} in ${REPO_DIR}"
    git -C "${REPO_DIR}" fetch --quiet origin "${REPO_BRANCH}" || true
    git -C "${REPO_DIR}" checkout --quiet "${REPO_BRANCH}" || true
    git -C "${REPO_DIR}" pull --quiet --ff-only || true
fi

# --- Vault ------------------------------------------------------------------
#
# Must run AFTER the clone/pull: the destination directory only exists once the
# repo is there, and this file is deliberately not in the repo.
#
# control-node/vault/ is bind-mounted at ${VAULT_SRC}. The vault file is
# gitignored because Tav_Lab is public, which means the container's clone never
# contains it — copying it into the group_vars tree is what makes Ansible
# auto-load it. Copy rather than mount straight into the repo path: the repo
# lives in a named volume, and nesting a bind mount inside it is a subtlety that
# breaks quietly when the volume is recreated.
#
# The destination is the group_vars/all/ DIRECTORY, and that is load-bearing.
# Ansible's group_vars loader does not glob: for group `all` it looks for exactly
# `all`, `all.yml`, `all.yaml` or `all.json`. A file named `all.vault.yml` has the
# basename `all.vault`, which matches no group, so it is silently ignored — no
# warning, no error, just undefined variables and a preflight assert that blames
# the secrets for being absent. Inside a group DIRECTORY every file is loaded
# regardless of name, which is why group_vars/all/ exists at all (main.yml is the
# former group_vars/all.yml).
#
# The file stays encrypted; playbook runs still need --ask-vault-pass (or the
# optional password file below).
VAULT_SRC=/home/ansible/vault
VAULT_DST="${REPO_DIR}/ansible/inventory/group_vars/all"

mkdir -p "${VAULT_DST}"

shopt -s nullglob
vault_files=("${VAULT_SRC}"/*.vault.yml)
shopt -u nullglob

if [[ ${#vault_files[@]} -gt 0 ]]; then
    for v in "${vault_files[@]}"; do
        install -m 600 "${v}" "${VAULT_DST}/$(basename "${v}")"
        echo "[entrypoint] vault: installed $(basename "${v}") -> inventory/group_vars/all/"
    done
else
    echo "[entrypoint] WARNING: no *.vault.yml found in control-node/vault/" >&2
    echo "[entrypoint]   Expected control-node/vault/all.vault.yml on the host." >&2
    echo "[entrypoint]   playbooks/autobase.yml will fail its preflight assert on" >&2
    echo "[entrypoint]   vault_proxmox_api_token_secret until it is there." >&2
    echo "[entrypoint]   See control-node/README.md step 2b." >&2
fi

# Optional: control-node/vault/.vault_pass makes runs non-interactive.
#
# Worth having for two reasons beyond saving keystrokes. First, `--ask-vault-pass`
# uses getpass(), which needs to turn terminal echo off — redirect a run's output
# to a file and it warns "Can not control echo on the terminal", falls back, and
# the read comes back mangled as "Invalid vault password was provided". That makes
# capturing a log of a failing run surprisingly hard. Second, it is what any
# non-interactive caller (cron, CI) would need.
#
# The trade-off is real and is yours to make: this is the vault password sitting
# in cleartext on the workstation's disk. It buys convenience, not security — the
# encryption still protects the secrets in the public repo and in transit, which
# is what it was for. Omit the file and everything still works interactively.
if [[ -f "${VAULT_SRC}/.vault_pass" ]]; then
    export ANSIBLE_VAULT_PASSWORD_FILE="${VAULT_SRC}/.vault_pass"
    echo "[entrypoint] vault: using .vault_pass — runs are non-interactive"
fi

cd "${REPO_DIR}/ansible"
exec "$@"
